import fs from 'fs';
const content = fs.readFileSync('src/App.tsx', 'utf-8');
const lines = content.split('\n');

// The goal is to replace the messy section between the overall progress (3444) and the project table (3641)
const startMarker = '<div className="h-[180px] w-full relative">'; // Part of Tiến độ chung
const endMarker = 'Tình hình xử lý theo Dự án'; // Part of the project table

const startIndex = lines.findIndex(l => l.includes(startMarker));
const endIndex = lines.findIndex(l => l.includes(endMarker));

if (startIndex !== -1 && endIndex !== -1) {
    // Back up from endIndex to find the start of that div
    let actualEnd = endIndex;
    while (actualEnd > 0 && !lines[actualEnd].includes('<div className={cn(')) {
        actualEnd--;
    }
    
    // Back up from startIndex to find the start of its container
    let actualStart = startIndex;
    while (actualStart > 0 && !lines[actualStart].includes('<div className={cn(')) {
        actualStart--;
    }

    const newContent = [
        '                  <div className={cn(',
        '                    "backdrop-blur-md p-8 rounded-[3rem] border transition-all duration-500 flex flex-col group divide-y divide-slate-800/10",',
        '                    theme === \'light\' ? "bg-white border-slate-200 shadow-2xl shadow-slate-200/50" : "bg-slate-900/40 border-slate-800/50 shadow-2xl"',
        '                  )}>',
        '                    <div className="pb-8">',
        '                      <h3 className={cn("font-bold mb-6 font-serif text-xl italic flex items-center gap-3", theme === \'light\' ? "text-slate-900" : "text-white")}>',
        '                        <Filter size={18} className="text-festive-gold" />',
        '                        Tiến độ chung',
        '                      </h3>',
        '                      <div className="h-[180px] w-full relative">',
        '                        <ResponsiveContainer width="100%" height="100%">',
        '                          <PieChart>',
        '                            <Pie data={chartData} cx="50%" cy="50%" innerRadius={60} outerRadius={80} paddingAngle={5} dataKey="value">',
        '                              {chartData.map((entry, index) => (',
        '                                <Cell key={`cell-${index}`} fill={entry.color} />',
        '                              ))}',
        '                            </Pie>',
        '                          </PieChart>',
        '                        </ResponsiveContainer>',
        '                        <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">',
        '                          <span className={cn("text-2xl font-black italic font-serif", theme === \'light\' ? "text-slate-900" : "text-white")}>{kpis.total}</span>',
        '                          <span className="text-[8px] uppercase font-black text-slate-500 mt-1">Căn</span>',
        '                        </div>',
        '                      </div>',
        '                    </div>',
        '',
        '                    <div className="pt-8">',
        '                       <h3 className={cn("font-bold mb-6 font-serif text-xl italic flex items-center gap-3", theme === \'light\' ? "text-slate-900" : "text-white")}>',
        '                         <Wallet size={18} className="text-emerald-500" />',
        '                         Trạng thái Căn có vay',
        '                       </h3>',
        '                       {roleKpis.loanStatusStats.length > 0 ? (',
        '                         <div className="grid grid-cols-1 gap-4">',
        '                            <div className="h-[120px] w-full relative">',
        '                               <ResponsiveContainer width="100%" height="100%">',
        '                                 <PieChart>',
        '                                   <Pie data={roleKpis.loanStatusStats} cx="50%" cy="50%" innerRadius={40} outerRadius={55} paddingAngle={5} dataKey="value">',
        '                                     {roleKpis.loanStatusStats.map((entry: any, index: number) => (',
        '                                       <Cell key={`cell-loan-${index}`} fill={entry.color} />',
        '                                     ))}',
        '                                   </Pie>',
        '                                 </PieChart>',
        '                               </ResponsiveContainer>',
        '                            </div>',
        '                            <div className="flex flex-wrap gap-2">',
        '                               {roleKpis.loanStatusStats.map((s: any) => (',
        '                                 <div key={s.name} className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-slate-800/10 border border-slate-800/10">',
        '                                   <div className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: s.color }} />',
        '                                   <span className="text-[8px] text-slate-500 font-bold uppercase">{s.name}:</span>',
        '                                   <span className={cn("text-[9px] font-black", theme === \'light\' ? "text-slate-900" : "text-white")}>{s.value}</span>',
        '                                 </div>',
        '                               ))}',
        '                            </div>',
        '                         </div>',
        '                       ) : (',
        '                         <div className="py-10 text-center opacity-40">',
        '                            <p className="text-[10px] italic">Không có dữ liệu căn có vay</p>',
        '                         </div>',
        '                       )}',
        '                    </div>',
        '                  </div>',
        '                </div>',
        '',
        '                <div className={cn(',
        '                  "backdrop-blur-xl rounded-3xl shadow-2xl border transition-all overflow-hidden",',
        '                  theme === \'light\' ? "bg-white border-slate-200" : "bg-slate-900/20 shadow-2xl border-slate-800/50"',
        '                )}>',
        '                  <div className={cn("p-6 border-b flex items-center justify-between", theme === \'light\' ? "border-slate-100 bg-slate-50" : "border-slate-800/50")}>',
        '                    <div className="flex items-center gap-4">',
        '                      <h3 className={cn("font-bold font-serif text-xl italic", theme === \'light\' ? "text-slate-900" : "text-white")}>Phân tích Hiệu suất & Điểm nghẽn (Giai đoạn 1 - 6)</h3>',
        '                      <div className="flex items-center gap-2 bg-slate-800/20 rounded-lg p-1 border border-slate-700/30">',
        '                        <Clock size={12} className="text-slate-500 ml-1" />',
        '                        <span className="text-[10px] font-black uppercase text-slate-400 px-2 italic">So sánh SLA Thực tế vs Kế hoạch</span>',
        '                      </div>',
        '                    </div>',
        '                  </div>',
        '                  <div className="p-8">',
        '                    <div className="grid grid-cols-1 xl:grid-cols-4 gap-8">',
        '                       <div className="xl:col-span-3">',
        '                          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">',
        '                            {roleKpis.admin.slaStats.map((item, idx) => (',
        '                              <div key={item.label} className={cn(',
        '                                "p-6 rounded-[2rem] border transition-all hover:border-festive-gold/50 duration-300",',
        '                                theme === \'light\' ? "bg-slate-50 border-slate-100 shadow-sm" : "bg-slate-800/40 border-slate-700/30 shadow-xl"',
        '                              )}>',
        '                                 <div className="flex justify-between items-start mb-5">',
        '                                    <div className="flex items-center gap-3">',
        '                                       <div className="w-10 h-10 rounded-2xl bg-slate-900 flex items-center justify-center text-xs font-black text-slate-500 shadow-xl border border-slate-800">',
        '                                          {idx + 1}',
        '                                       </div>',
        '                                       <div>',
        '                                          <p className={cn("text-[9px] font-black uppercase tracking-widest", theme === \'light\' ? "text-slate-400" : "text-slate-500")}>Giai đoạn</p>',
        '                                          <p className={cn("text-xs font-black italic", theme === \'light\' ? "text-slate-900" : "text-white")}>{item.label}</p>',
        '                                       </div>',
        '                                    </div>',
        '                                    <div className="text-right">',
        '                                       <p className="text-[9px] font-mono text-slate-500 mb-1 uppercase tracking-tighter">SLA: {item.sla}d</p>',
        '                                       <p className={cn("text-lg font-black leading-none", item.avg > item.sla ? "text-rose-500" : "text-emerald-500")}>{item.avg}d</p>',
        '                                    </div>',
        '                                 </div>',
        '                                 <div className="h-1.5 w-full bg-slate-800/20 rounded-full overflow-hidden">',
        '                                    <div className={cn("h-full rounded-full transition-all duration-700", item.color)} style={{ width: `${Math.min(100, (item.avg / item.sla) * 100)}%` }} />',
        '                                 </div>',
        '                                 {item.avg > item.sla && (',
        '                                   <div className="mt-4 flex items-center gap-2 p-2 rounded-xl bg-rose-500/5 border border-rose-500/10">',
        '                                      <AlertTriangle size={12} className="text-rose-500" />',
        '                                      <p className="text-[9px] text-rose-500 font-bold italic">Vượt {item.avg - item.sla} ngày</p>',
        '                                   </div>',
        '                                 )}',
        '                              </div>',
        '                            ))}',
        '                          </div>',
        '                       </div>',
        '',
        '                       <div className={cn(',
        '                         "p-6 rounded-[2.5rem] border flex flex-col shadow-2xl space-y-6",',
        '                         theme === \'light\' ? "bg-slate-900 text-white border-slate-800" : "bg-slate-800/60 border-slate-700/50 shadow-black/40"',
        '                       )}>',
        '                          <div className="flex items-center gap-3">',
        '                             <div className="w-10 h-10 rounded-2xl bg-amber-500/20 flex items-center justify-center">',
        '                                <Zap size={20} className="text-amber-500" />',
        '                             </div>',
        '                             <h4 className="text-xs font-black uppercase tracking-widest italic text-white">Điểm nghẽn</h4>',
        '                          </div>',
        '                          ',
        '                          <div className="space-y-4 flex-1 overflow-y-auto max-h-[400px] pr-2 custom-scrollbar">',
        '                            {roleKpis.admin.warnings.map((warning, idx) => {',
        '                              const WarningIcon = warning.icon;',
        '                              return (',
        '                                <div key={idx} className="p-4 rounded-2xl bg-slate-900/40 border border-slate-800/50 hover:border-slate-700 transition-all">',
        '                                  <div className="flex gap-3">',
        '                                    <div className="shrink-0 w-8 h-8 rounded-xl bg-slate-900 flex items-center justify-center">',
        '                                       <WarningIcon className={cn(warning.color === \'rose\' ? \'text-rose-500\' : \'text-amber-500\')} size={14} />',
        '                                    </div>',
        '                                    <div className="flex-1">',
        '                                       <p className="text-[11px] font-black text-white leading-tight mb-1">{warning.title}</p>',
        '                                       <p className="text-[10px] text-slate-500 leading-relaxed font-medium">{warning.desc}</p>',
        '                                    </div>',
        '                                  </div>',
        '                                </div>',
        '                              );',
        '                            })}',
        '                            ',
        '                            {roleKpis.admin.warnings.length === 0 && (',
        '                               <div className="py-20 opacity-30 text-center">',
        '                                  <CheckCircle2 size={32} className="text-emerald-500 mx-auto mb-3" />',
        '                                  <p className="text-[10px] italic font-black uppercase tracking-widest text-white">Tối ưu</p>',
        '                               </div>',
        '                            )}',
        '                          </div>',
        '                          ',
        '                          <div className="pt-6 border-t border-slate-800/50">',
        '                             <div className="p-4 rounded-2xl bg-festive-gold/10 border border-festive-gold/20">',
        '                                <p className="text-[9px] font-black text-festive-gold uppercase tracking-[0.2em] mb-2 text-center underline decoration-festive-gold/30 underline-offset-4">Gợi ý từ AI</p>',
        '                                <p className="text-[10px] text-slate-400 italic leading-relaxed text-center font-medium">',
        '                                  Tập trung giải quyết các hồ sơ GĐ1 & GĐ4 để rút ngắn thời gian bàn giao sổ.',
        '                                </p>',
        '                             </div>',
        '                          </div>',
        '                       </div>',
        '                    </div>',
        '                  </div>',
        '                </div>',
        '',
    ];

    lines.splice(actualStart, (actualEnd - actualStart), ...newContent);
    fs.writeFileSync('src/App.tsx', lines.join('\n'));
    console.log('Successfully refactored App.tsx');
} else {
    console.error('Failed to find markers', { startIndex, endIndex });
    process.exit(1);
}
